version: "3.9"
<<<<<<< HEAD
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    networks:
      - monitoring
=======

services:

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
>>>>>>> c1b3efe3c488ba939147a211f2c6a67544c753e1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: elevator_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d elevator_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana:11.1.0
    restart: unless-stopped
<<<<<<< HEAD
    networks:
      - monitoring
=======
>>>>>>> c1b3efe3c488ba939147a211f2c6a67544c753e1
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/elevator_dashboard.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      timescaledb:
        condition: service_healthy

<<<<<<< HEAD
networks:
  monitoring:
    driver: bridge

volumes:
  timescale_data:
  grafana_data:
=======
volumes:
  timescale_data:
  grafana_data:
>>>>>>> c1b3efe3c488ba939147a211f2c6a67544c753e1
